server:
  port: 18082
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    '[com.widus.springbootauth]': DEBUG
    '[org.springframework]': TRACE
