server:
  port: 18080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    '[org.springframework]': DEBUG
#    '[org.springframework]': TRACE